# Generated by Django 3.2.12 on 2022-12-05 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produkty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateField(auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='Szczegoly_zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkty.produkty')),
                ('id_zamowienia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.zamowienia')),
            ],
        ),
        migrations.CreateModel(
            name='Faktury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateField(auto_created=True)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_zamowienia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.szczegoly_zamowienia')),
            ],
        ),
    ]
