# Generated by Django 3.2.12 on 2022-12-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_remove_produkty_zdjecie'),
        ('zamowienia', '0003_zamowienia_id_uzytkownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szczegoly_zamowienia',
            name='id_produktu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.produkty'),
        ),
    ]
