# Generated by Django 3.2.12 on 2022-12-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0004_alter_szczegoly_zamowienia_id_produktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktury',
            name='id_zamowienia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zamowienia.zamowienia'),
        ),
    ]
