# Generated by Django 3.2.12 on 2022-12-05 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Producenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_producenta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opis', models.TextField(blank=True, max_length=255, null=True)),
                ('zdjecie', models.ImageField(upload_to='')),
                ('id_producenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkty.producenci')),
            ],
        ),
        migrations.CreateModel(
            name='Opinie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateField(auto_created=True)),
                ('tresc', models.CharField(max_length=255)),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.produkty')),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria_produktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kategorii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.kategorie')),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produkty.produkty')),
            ],
        ),
    ]
