# Generated by Django 3.2.12 on 2022-12-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0002_remove_produkty_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinie',
            name='data_wystawienia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
