# Generated by Django 3.2.12 on 2022-11-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=70)),
                ('powiat', models.CharField(max_length=50)),
                ('wojewodztwo', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(blank=True, max_length=70, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontakty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('id_adresu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.adresy')),
                ('id_kontaktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.kontakty')),
            ],
        ),
    ]
