# Generated by Django 3.2.12 on 2022-12-05 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.BooleanField()),
                ('staff', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kontakty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('id_uzytkownika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=70)),
                ('powiat', models.CharField(max_length=50)),
                ('wojewodztwo', models.CharField(max_length=50)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(blank=True, max_length=70, null=True)),
                ('numer_domu', models.IntegerField()),
                ('numer_lokalu', models.IntegerField(blank=True, null=True)),
                ('id_uzytkownika', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
