# Generated by Django 3.2.12 on 2022-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresy',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='miejscowosc',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='numer_domu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='powiat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adresy',
            name='wojewodztwo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
