# Generated by Django 3.2.12 on 2022-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_auto_20221207_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownicy',
            name='admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='staff',
            field=models.BooleanField(null=True),
        ),
    ]
